### ISSUE TITLE
Creating theme from Xresources causes error.

### ISSUE THREAD

**Issue by rytone** [actionless/oomox#37]
I get this error when selecting the xresources option in the GUI:
```
Traceback (most recent call last):
  File "/opt/oomox/gui/presets_list.py", line 23, in on_preset_select
    self.current_theme, self.current_preset_path
  File "/opt/oomox/gui/main.py", line 118, in on_preset_selected
    self.colorscheme = read_colorscheme_from_path(selected_preset_path)
  File "/opt/oomox/gui/helpers.py", line 212, in read_colorscheme_from_path
    colorscheme = bash_preprocess(preset_path)
  File "/opt/oomox/gui/helpers.py", line 189, in bash_preprocess
    value = lines[i]
IndexError: list index out of range
```
I'm not sure if this is causing it, but my .Xresources is a symlink to a file in another directory.

**Comment by actionless** [comment]
do you have `xrdb` installed?

**Comment by rytone** [comment]
yeah

**Comment by actionless** [comment]
please paste the output of `xrdb -query`

**Comment by actionless** [comment]
it expects colors without dot, ie https://github.com/actionless/oomox/blob/master/colors/xresources#L8
