### ISSUE TITLE
Can't open gui

### ISSUE THREAD

**Issue by Talor-A** [actionless/oomox#42]
Hi, I've tried installing oomox from .deb and git, and I get this error when trying to open the gui. the cli seems to work okay. I'm on xfce on ubuntu 14.04.

```
Traceback (most recent call last):
  File "/opt/oomox/gui/preview.py", line 214, in _override_css_style
    os.path.join(script_dir, "theme.css")
gi._glib.GError: theme.css:74:16'outline-radius' is not a valid property name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/oomox/gui/__main__.py", line 5, in <module>
    main()
  File "/opt/oomox/gui/main.py", line 205, in main
    win = MainWindow()
  File "/opt/oomox/gui/main.py", line 199, in __init__
    self.preview = ThemePreview()
  File "/opt/oomox/gui/preview.py", line 126, in __init__
    self._override_css_style()
  File "/opt/oomox/gui/preview.py", line 216, in _override_css_style
    except GLib.Error as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by actionless** [comment]
The latest version works with GTK+ 3.18 or higher.
The previous one (0.22.0) works with 3.16 or higher.
