### ISSUE TITLE
SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by eater** [actionless/oomox#66]
Just installed (with all the prerequisites listed) on Ubuntu 15.04. When I run gui.sh (as either normal or superuser), here's what I get:

```
** (__main__.py:21028): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-XhRapCypAB: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/src/oomox/gui/__main__.py", line 1, in <module>
    from .main import main
  File "/usr/local/src/oomox/gui/main.py", line 16, in <module>
    from .preview import ThemePreview
  File "/usr/local/src/oomox/gui/preview.py", line 318
    *self.get_menu_widgets(self.menubar),
               ^
SyntaxError: can use starred expression only as assignment target
```

**Comment by actionless** [comment]
python version?

**Comment by actionless** [comment]
that was implemented only in python3.5 (https://www.python.org/dev/peps/pep-0448/)

**Comment by eater** [comment]
Aha, I've got Python 3.4.

**Comment by actionless** [comment]
thanks for reporting!

**Comment by cwendling** [comment]
Oops, sorry about that
